const CONSTANTS = {
  MIN_LOTTO_NUMBER: 1,
  MAX_LOTTO_NUMBER: 45,
  LOTTO_NUMBER_COUNT: 6,
  PRICE_PER_TICKET: 1000,
};

const ERROR = {
    ERROR_MSG_INVALID_NUMBER_COUNT: "[ERROR] 로또 번호는 6개여야 합니다.",
    ERROR_MSG_DUPLICATE_NUMBER : "[ERROR] 로또 번호는 중복될 수 없습니다.", 
    ERROR_MSG_NUMBER_OUT_OF_RANGE : "[ERROR] 로또 번호는 1부터 45 사이의 숫자여야 합니다."
}

export{CONSTANTS,ERROR}